
#include <blend2d.h>
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>

#define ULong64_t size_t
#define Long64_t intptr_t

namespace py = pybind11;

PYBIND11_MODULE(pyblend2d, m)
{
    m.doc() = "Blend2D bindings";
    py::class_<BLBox>(m, "BLBox")
        .def(py::init<>())
        .def(py::init<const BLBox &>())
        .def(py::init<const BLBoxI &>())
        .def(py::init<double, double, double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("contains", py::overload_cast<double, double>(&BLBox::contains, py::const_))
        .def("contains", py::overload_cast<const BLPoint &>(&BLBox::contains, py::const_))
        .def("equals", (&BLBox::equals))
        .def("reset", py::overload_cast<>(&BLBox::reset))
        .def("reset", py::overload_cast<const BLBox &>(&BLBox::reset))
        .def("reset", py::overload_cast<double, double, double, double>(&BLBox::reset));
    py::class_<BLMatrix2D>(m, "BLMatrix2D")
        .def(py::init<>())
        .def(py::init<const BLMatrix2D &>())
        .def(py::init<double, double, double, double, double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("determinant", (&BLMatrix2D::determinant))
        .def("equals", (&BLMatrix2D::equals))
        .def("invert", py::overload_cast<>(&BLMatrix2D::invert))
        .def("invert", py::overload_cast<BLMatrix2D &, const BLMatrix2D &>(&BLMatrix2D::invert))
        .def("makeIdentity", (&BLMatrix2D::makeIdentity))
        .def("makeRotation", py::overload_cast<double>(&BLMatrix2D::makeRotation))
        .def("makeRotation", py::overload_cast<double, double, double>(&BLMatrix2D::makeRotation))
        .def("makeRotation", py::overload_cast<double, const BLPoint &>(&BLMatrix2D::makeRotation))
        .def("makeScaling", py::overload_cast<double>(&BLMatrix2D::makeScaling))
        .def("makeScaling", py::overload_cast<double, double>(&BLMatrix2D::makeScaling))
        .def("makeScaling", py::overload_cast<const BLPointI &>(&BLMatrix2D::makeScaling))
        .def("makeScaling", py::overload_cast<const BLPoint &>(&BLMatrix2D::makeScaling))
        .def("makeSinCos", py::overload_cast<double, double, double, double>(&BLMatrix2D::makeSinCos))
        .def("makeSinCos", py::overload_cast<double, double, const BLPoint &>(&BLMatrix2D::makeSinCos))
        .def("makeSkewing", py::overload_cast<double, double>(&BLMatrix2D::makeSkewing))
        .def("makeSkewing", py::overload_cast<const BLPoint &>(&BLMatrix2D::makeSkewing))
        .def("makeTranslation", py::overload_cast<double, double>(&BLMatrix2D::makeTranslation))
        .def("makeTranslation", py::overload_cast<const BLPointI &>(&BLMatrix2D::makeTranslation))
        .def("makeTranslation", py::overload_cast<const BLPoint &>(&BLMatrix2D::makeTranslation))
        .def("mapPoint", py::overload_cast<double, double>(&BLMatrix2D::mapPoint, py::const_))
        .def("mapPoint", py::overload_cast<const BLPoint &>(&BLMatrix2D::mapPoint, py::const_))
        .def("mapVector", py::overload_cast<double, double>(&BLMatrix2D::mapVector, py::const_))
        .def("mapVector", py::overload_cast<const BLPoint &>(&BLMatrix2D::mapVector, py::const_))
        .def("postRotate", py::overload_cast<double>(&BLMatrix2D::postRotate))
        .def("postRotate", py::overload_cast<double, double, double>(&BLMatrix2D::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPointI &>(&BLMatrix2D::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPoint &>(&BLMatrix2D::postRotate))
        .def("postScale", py::overload_cast<double>(&BLMatrix2D::postScale))
        .def("postScale", py::overload_cast<double, double>(&BLMatrix2D::postScale))
        .def("postScale", py::overload_cast<const BLPointI &>(&BLMatrix2D::postScale))
        .def("postScale", py::overload_cast<const BLPoint &>(&BLMatrix2D::postScale))
        .def("postSkew", py::overload_cast<double, double>(&BLMatrix2D::postSkew))
        .def("postSkew", py::overload_cast<const BLPoint &>(&BLMatrix2D::postSkew))
        .def("postTransform", (&BLMatrix2D::postTransform))
        .def("postTranslate", py::overload_cast<double, double>(&BLMatrix2D::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPointI &>(&BLMatrix2D::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPoint &>(&BLMatrix2D::postTranslate))
        .def("reset", py::overload_cast<>(&BLMatrix2D::reset))
        .def("reset", py::overload_cast<const BLMatrix2D &>(&BLMatrix2D::reset))
        .def("reset", py::overload_cast<double, double, double, double, double, double>(&BLMatrix2D::reset))
        .def("resetToRotation", py::overload_cast<double>(&BLMatrix2D::resetToRotation))
        .def("resetToRotation", py::overload_cast<double, double, double>(&BLMatrix2D::resetToRotation))
        .def("resetToRotation", py::overload_cast<double, const BLPoint &>(&BLMatrix2D::resetToRotation))
        .def("resetToScaling", py::overload_cast<double>(&BLMatrix2D::resetToScaling))
        .def("resetToScaling", py::overload_cast<double, double>(&BLMatrix2D::resetToScaling))
        .def("resetToScaling", py::overload_cast<const BLPointI &>(&BLMatrix2D::resetToScaling))
        .def("resetToScaling", py::overload_cast<const BLPoint &>(&BLMatrix2D::resetToScaling))
        .def("resetToSinCos", py::overload_cast<double, double, double, double>(&BLMatrix2D::resetToSinCos))
        .def("resetToSinCos", py::overload_cast<double, double, const BLPoint &>(&BLMatrix2D::resetToSinCos))
        .def("resetToSkewing", py::overload_cast<double, double>(&BLMatrix2D::resetToSkewing))
        .def("resetToSkewing", py::overload_cast<const BLPoint &>(&BLMatrix2D::resetToSkewing))
        .def("resetToTranslation", py::overload_cast<double, double>(&BLMatrix2D::resetToTranslation))
        .def("resetToTranslation", py::overload_cast<const BLPointI &>(&BLMatrix2D::resetToTranslation))
        .def("resetToTranslation", py::overload_cast<const BLPoint &>(&BLMatrix2D::resetToTranslation))
        .def("rotate", py::overload_cast<double>(&BLMatrix2D::rotate))
        .def("rotate", py::overload_cast<double, double, double>(&BLMatrix2D::rotate))
        .def("rotate", py::overload_cast<double, const BLPointI &>(&BLMatrix2D::rotate))
        .def("rotate", py::overload_cast<double, const BLPoint &>(&BLMatrix2D::rotate))
        .def("scale", py::overload_cast<double>(&BLMatrix2D::scale))
        .def("scale", py::overload_cast<double, double>(&BLMatrix2D::scale))
        .def("scale", py::overload_cast<const BLPointI &>(&BLMatrix2D::scale))
        .def("scale", py::overload_cast<const BLPoint &>(&BLMatrix2D::scale))
        .def("skew", py::overload_cast<double, double>(&BLMatrix2D::skew))
        .def("skew", py::overload_cast<const BLPoint &>(&BLMatrix2D::skew))
        .def("transform", (&BLMatrix2D::transform))
        .def("translate", py::overload_cast<double, double>(&BLMatrix2D::translate))
        .def("translate", py::overload_cast<const BLPointI &>(&BLMatrix2D::translate))
        .def("translate", py::overload_cast<const BLPoint &>(&BLMatrix2D::translate))
        .def("type", (&BLMatrix2D::type));
    py::class_<BLImage>(m, "BLImage")
        .def(py::init<>())
        .def(py::init<const BLImage &>())
        .def(py::init<BLImageImpl *>())
        .def(py::init<int, int, unsigned int>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("assign", py::overload_cast<const BLImage &>(&BLImage::assign))
        .def("assignDeep", (&BLImage::assignDeep))
        .def("convert", (&BLImage::convert))
        .def("create", (&BLImage::create))
        .def("createFromData", (&BLImage::createFromData))
        .def("empty", (&BLImage::empty))
        .def("equals", (&BLImage::equals))
        .def("format", (&BLImage::format))
        .def("getData", (&BLImage::getData))
        .def("height", (&BLImage::height))
        .def("isNone", (&BLImage::isNone))
        .def("makeMutable", py::overload_cast<>(&BLImage::makeMutable))
        .def("makeMutable", py::overload_cast<BLImageData *>(&BLImage::makeMutable))
        .def("none", (&BLImage::none))
        .def("readFromData", py::overload_cast<const void *, ULong64_t>(&BLImage::readFromData))
        .def("readFromData", py::overload_cast<const void *, ULong64_t, const BLArray<BLImageCodec> &>(&BLImage::readFromData))
        .def("readFromData", py::overload_cast<const BLArray<unsigned char> &>(&BLImage::readFromData))
        .def("readFromData", py::overload_cast<const BLArray<unsigned char> &, const BLArray<BLImageCodec> &>(&BLImage::readFromData))
        .def("readFromData", py::overload_cast<const BLArrayView<unsigned char> &>(&BLImage::readFromData))
        .def("readFromData", py::overload_cast<const BLArrayView<unsigned char> &, const BLArray<BLImageCodec> &>(&BLImage::readFromData))
        .def("readFromFile", py::overload_cast<const char *>(&BLImage::readFromFile))
        .def("readFromFile", py::overload_cast<const char *, const BLArray<BLImageCodec> &>(&BLImage::readFromFile))
        .def("reset", (&BLImage::reset))
        .def("scale", (&BLImage::scale))
        .def("size", (&BLImage::size))
        .def("swap", (&BLImage::swap))
        .def("width", (&BLImage::width))
        .def("writeToData", (&BLImage::writeToData))
        .def("writeToFile", (&BLImage::writeToFile));
    py::class_<BLPoint>(m, "BLPoint")
        .def(py::init<>())
        .def(py::init<const BLPoint &>())
        .def(py::init<const BLPointI &>())
        .def(py::init<double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLPoint::equals))
        .def("reset", py::overload_cast<>(&BLPoint::reset))
        .def("reset", py::overload_cast<const BLPoint &>(&BLPoint::reset))
        .def("reset", py::overload_cast<double, double>(&BLPoint::reset));
    py::class_<BLPointI>(m, "BLPointI")
        .def(py::init<>())
        .def(py::init<const BLPointI &>())
        .def(py::init<int, int>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLPointI::equals))
        .def("reset", py::overload_cast<>(&BLPointI::reset))
        .def("reset", py::overload_cast<const BLPointI &>(&BLPointI::reset))
        .def("reset", py::overload_cast<int, int>(&BLPointI::reset));
    py::class_<BLContext>(m, "BLContext")
        .def(py::init<>())
        .def(py::init<const BLContext &>())
        .def(py::init<BLContextImpl *>())
        .def(py::init<BLImage &>())
        .def(py::init<BLImage &, const BLContextCreateInfo &>())
        .def(py::init<BLImage &, const BLContextCreateInfo *>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("_applyMatrixOp", (&BLContext::_applyMatrixOp))
        .def("approximationOptions", (&BLContext::approximationOptions))
        .def("assign", py::overload_cast<const BLContext &>(&BLContext::assign))
        .def("begin", py::overload_cast<BLImage &>(&BLContext::begin))
        .def("begin", py::overload_cast<BLImage &, const BLContextCreateInfo &>(&BLContext::begin))
        .def("begin", py::overload_cast<BLImage &, const BLContextCreateInfo *>(&BLContext::begin))
        .def("blitImage", py::overload_cast<const BLPoint &, const BLImage &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLPoint &, const BLImage &, const BLRectI &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLPointI &, const BLImage &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLPointI &, const BLImage &, const BLRectI &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLRect &, const BLImage &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLRect &, const BLImage &, const BLRectI &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLRectI &, const BLImage &>(&BLContext::blitImage))
        .def("blitImage", py::overload_cast<const BLRectI &, const BLImage &, const BLRectI &>(&BLContext::blitImage))
        .def("clearAll", (&BLContext::clearAll))
        .def("clearRect", py::overload_cast<const BLRectI &>(&BLContext::clearRect))
        .def("clearRect", py::overload_cast<const BLRect &>(&BLContext::clearRect))
        .def("clearRect", py::overload_cast<double, double, double, double>(&BLContext::clearRect))
        .def("clipToRect", py::overload_cast<const BLRectI &>(&BLContext::clipToRect))
        .def("clipToRect", py::overload_cast<const BLRect &>(&BLContext::clipToRect))
        .def("clipToRect", py::overload_cast<double, double, double, double>(&BLContext::clipToRect))
        .def("compOp", (&BLContext::compOp))
        .def("contextType", (&BLContext::contextType))
        .def("end", (&BLContext::end))
        .def("equals", (&BLContext::equals))
        .def("fillAll", (&BLContext::fillAll))
        .def("fillAlpha", (&BLContext::fillAlpha))
        .def("fillBox", py::overload_cast<const BLBox &>(&BLContext::fillBox))
        .def("fillBox", py::overload_cast<const BLBoxI &>(&BLContext::fillBox))
        .def("fillBox", py::overload_cast<double, double, double, double>(&BLContext::fillBox))
        .def("fillBoxArray", py::overload_cast<const BLArrayView<BLBox> &>(&BLContext::fillBoxArray))
        .def("fillBoxArray", py::overload_cast<const BLBox *, ULong64_t>(&BLContext::fillBoxArray))
        .def("fillBoxArray", py::overload_cast<const BLArrayView<BLBoxI> &>(&BLContext::fillBoxArray))
        .def("fillBoxArray", py::overload_cast<const BLBoxI *, ULong64_t>(&BLContext::fillBoxArray))
        .def("fillChord", py::overload_cast<const BLArc &>(&BLContext::fillChord))
        .def("fillChord", py::overload_cast<double, double, double, double, double>(&BLContext::fillChord))
        .def("fillChord", py::overload_cast<double, double, double, double, double, double>(&BLContext::fillChord))
        .def("fillCircle", py::overload_cast<const BLCircle &>(&BLContext::fillCircle))
        .def("fillCircle", py::overload_cast<double, double, double>(&BLContext::fillCircle))
        .def("fillEllipse", py::overload_cast<const BLEllipse &>(&BLContext::fillEllipse))
        .def("fillEllipse", py::overload_cast<double, double, double, double>(&BLContext::fillEllipse))
        .def("fillGeometry", (&BLContext::fillGeometry))
        .def("fillGlyphRun", py::overload_cast<const BLPointI &, const BLFont &, const BLGlyphRun &>(&BLContext::fillGlyphRun))
        .def("fillGlyphRun", py::overload_cast<const BLPoint &, const BLFont &, const BLGlyphRun &>(&BLContext::fillGlyphRun))
        .def("fillPath", (&BLContext::fillPath))
        .def("fillPie", py::overload_cast<const BLArc &>(&BLContext::fillPie))
        .def("fillPie", py::overload_cast<double, double, double, double, double>(&BLContext::fillPie))
        .def("fillPie", py::overload_cast<double, double, double, double, double, double>(&BLContext::fillPie))
        .def("fillPolygon", py::overload_cast<const BLArrayView<BLPoint> &>(&BLContext::fillPolygon))
        .def("fillPolygon", py::overload_cast<const BLPoint *, ULong64_t>(&BLContext::fillPolygon))
        .def("fillPolygon", py::overload_cast<const BLArrayView<BLPointI> &>(&BLContext::fillPolygon))
        .def("fillPolygon", py::overload_cast<const BLPointI *, ULong64_t>(&BLContext::fillPolygon))
        .def("fillRect", py::overload_cast<const BLRectI &>(&BLContext::fillRect))
        .def("fillRect", py::overload_cast<const BLRect &>(&BLContext::fillRect))
        .def("fillRect", py::overload_cast<double, double, double, double>(&BLContext::fillRect))
        .def("fillRectArray", py::overload_cast<const BLArrayView<BLRect> &>(&BLContext::fillRectArray))
        .def("fillRectArray", py::overload_cast<const BLRect *, ULong64_t>(&BLContext::fillRectArray))
        .def("fillRectArray", py::overload_cast<const BLArrayView<BLRectI> &>(&BLContext::fillRectArray))
        .def("fillRectArray", py::overload_cast<const BLRectI *, ULong64_t>(&BLContext::fillRectArray))
        .def("fillRegion", (&BLContext::fillRegion))
        .def("fillRoundRect", py::overload_cast<const BLRoundRect &>(&BLContext::fillRoundRect))
        .def("fillRoundRect", py::overload_cast<const BLRect &, double>(&BLContext::fillRoundRect))
        .def("fillRoundRect", py::overload_cast<const BLRect &, double, double>(&BLContext::fillRoundRect))
        .def("fillRoundRect", py::overload_cast<double, double, double, double, double>(&BLContext::fillRoundRect))
        .def("fillRoundRect", py::overload_cast<double, double, double, double, double, double>(&BLContext::fillRoundRect))
        .def("fillRule", (&BLContext::fillRule))
        .def("fillStyleType", (&BLContext::fillStyleType))
        .def("fillTriangle", py::overload_cast<const BLTriangle &>(&BLContext::fillTriangle))
        .def("fillTriangle", py::overload_cast<double, double, double, double, double, double>(&BLContext::fillTriangle))
        .def("fillUtf16Text", py::overload_cast<const BLPointI &, const BLFont &, const unsigned short *, ULong64_t>(&BLContext::fillUtf16Text))
        .def("fillUtf16Text", py::overload_cast<const BLPoint &, const BLFont &, const unsigned short *, ULong64_t>(&BLContext::fillUtf16Text))
        .def("fillUtf32Text", py::overload_cast<const BLPointI &, const BLFont &, const unsigned int *, ULong64_t>(&BLContext::fillUtf32Text))
        .def("fillUtf32Text", py::overload_cast<const BLPoint &, const BLFont &, const unsigned int *, ULong64_t>(&BLContext::fillUtf32Text))
        .def("fillUtf8Text", py::overload_cast<const BLPointI &, const BLFont &, const char *, ULong64_t>(&BLContext::fillUtf8Text))
        .def("fillUtf8Text", py::overload_cast<const BLPoint &, const BLFont &, const char *, ULong64_t>(&BLContext::fillUtf8Text))
        .def("flattenMode", (&BLContext::flattenMode))
        .def("flattenTolerance", (&BLContext::flattenTolerance))
        .def("flush", (&BLContext::flush))
        .def("getFillStyle", py::overload_cast<BLRgba32 &>(&BLContext::getFillStyle, py::const_))
        .def("getFillStyle", py::overload_cast<BLRgba64 &>(&BLContext::getFillStyle, py::const_))
        .def("getFillStyle", py::overload_cast<BLPattern &>(&BLContext::getFillStyle, py::const_))
        .def("getFillStyle", py::overload_cast<BLGradient &>(&BLContext::getFillStyle, py::const_))
        .def("getStrokeStyle", py::overload_cast<BLRgba32 &>(&BLContext::getStrokeStyle, py::const_))
        .def("getStrokeStyle", py::overload_cast<BLRgba64 &>(&BLContext::getStrokeStyle, py::const_))
        .def("getStrokeStyle", py::overload_cast<BLPattern &>(&BLContext::getStrokeStyle, py::const_))
        .def("getStrokeStyle", py::overload_cast<BLGradient &>(&BLContext::getStrokeStyle, py::const_))
        .def("getStyle", py::overload_cast<unsigned int, BLRgba32 &>(&BLContext::getStyle, py::const_))
        .def("getStyle", py::overload_cast<unsigned int, BLRgba64 &>(&BLContext::getStyle, py::const_))
        .def("getStyle", py::overload_cast<unsigned int, BLPattern &>(&BLContext::getStyle, py::const_))
        .def("getStyle", py::overload_cast<unsigned int, BLGradient &>(&BLContext::getStyle, py::const_))
        .def("globalAlpha", (&BLContext::globalAlpha))
        .def("hints", (&BLContext::hints))
        .def("isNone", (&BLContext::isNone))
        .def("metaMatrix", (&BLContext::metaMatrix))
        .def("none", (&BLContext::none))
        .def("postRotate", py::overload_cast<double>(&BLContext::postRotate))
        .def("postRotate", py::overload_cast<double, double, double>(&BLContext::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPoint &>(&BLContext::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPointI &>(&BLContext::postRotate))
        .def("postScale", py::overload_cast<double>(&BLContext::postScale))
        .def("postScale", py::overload_cast<double, double>(&BLContext::postScale))
        .def("postScale", py::overload_cast<const BLPointI &>(&BLContext::postScale))
        .def("postScale", py::overload_cast<const BLPoint &>(&BLContext::postScale))
        .def("postSkew", py::overload_cast<double, double>(&BLContext::postSkew))
        .def("postSkew", py::overload_cast<const BLPoint &>(&BLContext::postSkew))
        .def("postTransform", (&BLContext::postTransform))
        .def("postTranslate", py::overload_cast<double, double>(&BLContext::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPointI &>(&BLContext::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPoint &>(&BLContext::postTranslate))
        .def("reset", (&BLContext::reset))
        .def("resetMatrix", (&BLContext::resetMatrix))
        .def("restore", py::overload_cast<>(&BLContext::restore))
        .def("restore", py::overload_cast<const BLContextCookie &>(&BLContext::restore))
        .def("restoreClipping", (&BLContext::restoreClipping))
        .def("rotate", py::overload_cast<double>(&BLContext::rotate))
        .def("rotate", py::overload_cast<double, double, double>(&BLContext::rotate))
        .def("rotate", py::overload_cast<double, const BLPoint &>(&BLContext::rotate))
        .def("rotate", py::overload_cast<double, const BLPointI &>(&BLContext::rotate))
        .def("save", py::overload_cast<>(&BLContext::save))
        .def("save", py::overload_cast<BLContextCookie &>(&BLContext::save))
        .def("savedStateCount", (&BLContext::savedStateCount))
        .def("scale", py::overload_cast<double>(&BLContext::scale))
        .def("scale", py::overload_cast<double, double>(&BLContext::scale))
        .def("scale", py::overload_cast<const BLPointI &>(&BLContext::scale))
        .def("scale", py::overload_cast<const BLPoint &>(&BLContext::scale))
        .def("setCompOp", (&BLContext::setCompOp))
        .def("setFillAlpha", (&BLContext::setFillAlpha))
        .def("setFillRule", (&BLContext::setFillRule))
        .def("setFillStyle", py::overload_cast<const BLRgba32 &>(&BLContext::setFillStyle))
        .def("setFillStyle", py::overload_cast<const BLRgba64 &>(&BLContext::setFillStyle))
        .def("setFillStyle", py::overload_cast<const BLGradient &>(&BLContext::setFillStyle))
        .def("setFillStyle", py::overload_cast<const BLPattern &>(&BLContext::setFillStyle))
        .def("setFillStyle", py::overload_cast<const BLVariant &>(&BLContext::setFillStyle))
        .def("setFlattenMode", (&BLContext::setFlattenMode))
        .def("setFlattenTolerance", (&BLContext::setFlattenTolerance))
        .def("setGlobalAlpha", (&BLContext::setGlobalAlpha))
        .def("setGradientQuality", (&BLContext::setGradientQuality))
        .def("setHint", (&BLContext::setHint))
        .def("setHints", (&BLContext::setHints))
        .def("setMatrix", (&BLContext::setMatrix))
        .def("setPatternQuality", (&BLContext::setPatternQuality))
        .def("setRenderingQuality", (&BLContext::setRenderingQuality))
        .def("setStrokeAlpha", (&BLContext::setStrokeAlpha))
        .def("setStrokeCap", (&BLContext::setStrokeCap))
        .def("setStrokeCaps", (&BLContext::setStrokeCaps))
        .def("setStrokeDashArray", (&BLContext::setStrokeDashArray))
        .def("setStrokeDashOffset", (&BLContext::setStrokeDashOffset))
        .def("setStrokeEndCap", (&BLContext::setStrokeEndCap))
        .def("setStrokeJoin", (&BLContext::setStrokeJoin))
        .def("setStrokeMiterLimit", (&BLContext::setStrokeMiterLimit))
        .def("setStrokeOptions", (&BLContext::setStrokeOptions))
        .def("setStrokeStartCap", (&BLContext::setStrokeStartCap))
        .def("setStrokeStyle", py::overload_cast<const BLRgba32 &>(&BLContext::setStrokeStyle))
        .def("setStrokeStyle", py::overload_cast<const BLRgba64 &>(&BLContext::setStrokeStyle))
        .def("setStrokeStyle", py::overload_cast<const BLPattern &>(&BLContext::setStrokeStyle))
        .def("setStrokeStyle", py::overload_cast<const BLGradient &>(&BLContext::setStrokeStyle))
        .def("setStrokeStyle", py::overload_cast<const BLVariant &>(&BLContext::setStrokeStyle))
        .def("setStrokeTransformOrder", (&BLContext::setStrokeTransformOrder))
        .def("setStrokeWidth", (&BLContext::setStrokeWidth))
        .def("setStyle", py::overload_cast<unsigned int, const BLGradient &>(&BLContext::setStyle))
        .def("setStyle", py::overload_cast<unsigned int, const BLPattern &>(&BLContext::setStyle))
        .def("setStyle", py::overload_cast<unsigned int, const BLImage &>(&BLContext::setStyle))
        .def("setStyle", py::overload_cast<unsigned int, const BLVariant &>(&BLContext::setStyle))
        .def("setStyle", py::overload_cast<unsigned int, const BLRgba32 &>(&BLContext::setStyle))
        .def("setStyle", py::overload_cast<unsigned int, const BLRgba64 &>(&BLContext::setStyle))
        .def("setStyleAlpha", (&BLContext::setStyleAlpha))
        .def("skew", py::overload_cast<double, double>(&BLContext::skew))
        .def("skew", py::overload_cast<const BLPoint &>(&BLContext::skew))
        .def("strokeAlpha", (&BLContext::strokeAlpha))
        .def("strokeArc", py::overload_cast<const BLArc &>(&BLContext::strokeArc))
        .def("strokeArc", py::overload_cast<double, double, double, double, double>(&BLContext::strokeArc))
        .def("strokeArc", py::overload_cast<double, double, double, double, double, double>(&BLContext::strokeArc))
        .def("strokeBox", py::overload_cast<const BLBox &>(&BLContext::strokeBox))
        .def("strokeBox", py::overload_cast<const BLBoxI &>(&BLContext::strokeBox))
        .def("strokeBox", py::overload_cast<double, double, double, double>(&BLContext::strokeBox))
        .def("strokeBoxArray", py::overload_cast<const BLArrayView<BLBox> &>(&BLContext::strokeBoxArray))
        .def("strokeBoxArray", py::overload_cast<const BLBox *, ULong64_t>(&BLContext::strokeBoxArray))
        .def("strokeBoxArray", py::overload_cast<const BLArrayView<BLBoxI> &>(&BLContext::strokeBoxArray))
        .def("strokeBoxArray", py::overload_cast<const BLBoxI *, ULong64_t>(&BLContext::strokeBoxArray))
        .def("strokeChord", py::overload_cast<const BLArc &>(&BLContext::strokeChord))
        .def("strokeChord", py::overload_cast<double, double, double, double, double>(&BLContext::strokeChord))
        .def("strokeChord", py::overload_cast<double, double, double, double, double, double>(&BLContext::strokeChord))
        .def("strokeCircle", py::overload_cast<const BLCircle &>(&BLContext::strokeCircle))
        .def("strokeCircle", py::overload_cast<double, double, double>(&BLContext::strokeCircle))
        .def("strokeDashArray", (&BLContext::strokeDashArray))
        .def("strokeDashOffset", (&BLContext::strokeDashOffset))
        .def("strokeEllipse", py::overload_cast<const BLEllipse &>(&BLContext::strokeEllipse))
        .def("strokeEllipse", py::overload_cast<double, double, double, double>(&BLContext::strokeEllipse))
        .def("strokeEndCap", (&BLContext::strokeEndCap))
        .def("strokeGeometry", (&BLContext::strokeGeometry))
        .def("strokeGlyphRun", py::overload_cast<const BLPointI &, const BLFont &, const BLGlyphRun &>(&BLContext::strokeGlyphRun))
        .def("strokeGlyphRun", py::overload_cast<const BLPoint &, const BLFont &, const BLGlyphRun &>(&BLContext::strokeGlyphRun))
        .def("strokeJoin", (&BLContext::strokeJoin))
        .def("strokeLine", py::overload_cast<const BLLine &>(&BLContext::strokeLine))
        .def("strokeLine", py::overload_cast<const BLPoint &, const BLPoint &>(&BLContext::strokeLine))
        .def("strokeLine", py::overload_cast<double, double, double, double>(&BLContext::strokeLine))
        .def("strokeMiterLimit", (&BLContext::strokeMiterLimit))
        .def("strokeOptions", (&BLContext::strokeOptions))
        .def("strokePath", (&BLContext::strokePath))
        .def("strokePie", py::overload_cast<const BLArc &>(&BLContext::strokePie))
        .def("strokePie", py::overload_cast<double, double, double, double, double>(&BLContext::strokePie))
        .def("strokePie", py::overload_cast<double, double, double, double, double, double>(&BLContext::strokePie))
        .def("strokePolygon", py::overload_cast<const BLArrayView<BLPoint> &>(&BLContext::strokePolygon))
        .def("strokePolygon", py::overload_cast<const BLPoint *, ULong64_t>(&BLContext::strokePolygon))
        .def("strokePolygon", py::overload_cast<const BLArrayView<BLPointI> &>(&BLContext::strokePolygon))
        .def("strokePolygon", py::overload_cast<const BLPointI *, ULong64_t>(&BLContext::strokePolygon))
        .def("strokePolyline", py::overload_cast<const BLArrayView<BLPoint> &>(&BLContext::strokePolyline))
        .def("strokePolyline", py::overload_cast<const BLPoint *, ULong64_t>(&BLContext::strokePolyline))
        .def("strokePolyline", py::overload_cast<const BLArrayView<BLPointI> &>(&BLContext::strokePolyline))
        .def("strokePolyline", py::overload_cast<const BLPointI *, ULong64_t>(&BLContext::strokePolyline))
        .def("strokeRect", py::overload_cast<const BLRect &>(&BLContext::strokeRect))
        .def("strokeRect", py::overload_cast<const BLRectI &>(&BLContext::strokeRect))
        .def("strokeRect", py::overload_cast<double, double, double, double>(&BLContext::strokeRect))
        .def("strokeRectArray", py::overload_cast<const BLArrayView<BLRect> &>(&BLContext::strokeRectArray))
        .def("strokeRectArray", py::overload_cast<const BLRect *, ULong64_t>(&BLContext::strokeRectArray))
        .def("strokeRectArray", py::overload_cast<const BLArrayView<BLRectI> &>(&BLContext::strokeRectArray))
        .def("strokeRectArray", py::overload_cast<const BLRectI *, ULong64_t>(&BLContext::strokeRectArray))
        .def("strokeRoundRect", py::overload_cast<const BLRoundRect &>(&BLContext::strokeRoundRect))
        .def("strokeRoundRect", py::overload_cast<const BLRect &, double>(&BLContext::strokeRoundRect))
        .def("strokeRoundRect", py::overload_cast<const BLRect &, double, double>(&BLContext::strokeRoundRect))
        .def("strokeRoundRect", py::overload_cast<double, double, double, double, double>(&BLContext::strokeRoundRect))
        .def("strokeRoundRect", py::overload_cast<double, double, double, double, double, double>(&BLContext::strokeRoundRect))
        .def("strokeStartCap", (&BLContext::strokeStartCap))
        .def("strokeStyleType", (&BLContext::strokeStyleType))
        .def("strokeTransformOrder", (&BLContext::strokeTransformOrder))
        .def("strokeTriangle", py::overload_cast<const BLTriangle &>(&BLContext::strokeTriangle))
        .def("strokeTriangle", py::overload_cast<double, double, double, double, double, double>(&BLContext::strokeTriangle))
        .def("strokeUtf16Text", py::overload_cast<const BLPointI &, const BLFont &, const unsigned short *, ULong64_t>(&BLContext::strokeUtf16Text))
        .def("strokeUtf16Text", py::overload_cast<const BLPoint &, const BLFont &, const unsigned short *, ULong64_t>(&BLContext::strokeUtf16Text))
        .def("strokeUtf32Text", py::overload_cast<const BLPointI &, const BLFont &, const unsigned int *, ULong64_t>(&BLContext::strokeUtf32Text))
        .def("strokeUtf32Text", py::overload_cast<const BLPoint &, const BLFont &, const unsigned int *, ULong64_t>(&BLContext::strokeUtf32Text))
        .def("strokeUtf8Text", py::overload_cast<const BLPointI &, const BLFont &, const char *, ULong64_t>(&BLContext::strokeUtf8Text))
        .def("strokeUtf8Text", py::overload_cast<const BLPoint &, const BLFont &, const char *, ULong64_t>(&BLContext::strokeUtf8Text))
        .def("strokeWidth", (&BLContext::strokeWidth))
        .def("styleAlpha", (&BLContext::styleAlpha))
        .def("styleType", (&BLContext::styleType))
        .def("targetHeight", (&BLContext::targetHeight))
        .def("targetSize", (&BLContext::targetSize))
        .def("targetWidth", (&BLContext::targetWidth))
        .def("transform", (&BLContext::transform))
        .def("translate", py::overload_cast<double, double>(&BLContext::translate))
        .def("translate", py::overload_cast<const BLPointI &>(&BLContext::translate))
        .def("translate", py::overload_cast<const BLPoint &>(&BLContext::translate))
        .def("userMatrix", (&BLContext::userMatrix))
        .def("userToMeta", (&BLContext::userToMeta));
    py::class_<BLRgba64>(m, "BLRgba64")
        .def(py::init<>())
        .def(py::init<const BLRgba64 &>())
        .def(py::init<ULong64_t>())
        .def(py::init<unsigned int, unsigned int, unsigned int, unsigned int>())
        .def(py::init<const BLRgba32 &>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLRgba64::equals))
        .def("isOpaque", (&BLRgba64::isOpaque))
        .def("isTransparent", (&BLRgba64::isTransparent))
        .def("reset", py::overload_cast<>(&BLRgba64::reset))
        .def("reset", py::overload_cast<ULong64_t>(&BLRgba64::reset))
        .def("reset", py::overload_cast<unsigned int, unsigned int, unsigned int, unsigned int>(&BLRgba64::reset))
        .def("reset", py::overload_cast<const BLRgba64 &>(&BLRgba64::reset))
        .def("reset", py::overload_cast<const BLRgba32 &>(&BLRgba64::reset));
    py::class_<BLRgba32>(m, "BLRgba32")
        .def(py::init<>())
        .def(py::init<const BLRgba32 &>())
        .def(py::init<unsigned int>())
        .def(py::init<const BLRgba64 &>())
        .def(py::init<unsigned int, unsigned int, unsigned int, unsigned int>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLRgba32::equals))
        .def("isOpaque", (&BLRgba32::isOpaque))
        .def("isTransparent", (&BLRgba32::isTransparent))
        .def("reset", py::overload_cast<>(&BLRgba32::reset))
        .def("reset", py::overload_cast<unsigned int>(&BLRgba32::reset))
        .def("reset", py::overload_cast<unsigned int, unsigned int, unsigned int, unsigned int>(&BLRgba32::reset))
        .def("reset", py::overload_cast<const BLRgba32 &>(&BLRgba32::reset))
        .def("reset", py::overload_cast<const BLRgba64 &>(&BLRgba32::reset));
    py::class_<BLPattern>(m, "BLPattern")
        .def(py::init<>())
        .def(py::init<const BLPattern &>())
        .def(py::init<BLPatternImpl *>())
        .def(py::init<const BLImage &, unsigned int>())
        .def(py::init<const BLImage &, unsigned int, const BLMatrix2D &>())
        .def(py::init<const BLImage &, const BLRectI &, unsigned int>())
        .def(py::init<const BLImage &, const BLRectI &, unsigned int, const BLMatrix2D &>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("_applyMatrixOp", (&BLPattern::_applyMatrixOp))
        .def("area", (&BLPattern::area))
        .def("assign", py::overload_cast<const BLPattern &>(&BLPattern::assign))
        .def("create", py::overload_cast<const BLImage &, unsigned int>(&BLPattern::create))
        .def("create", py::overload_cast<const BLImage &, unsigned int, const BLMatrix2D &>(&BLPattern::create))
        .def("create", py::overload_cast<const BLImage &, const BLRectI &, unsigned int>(&BLPattern::create))
        .def("create", py::overload_cast<const BLImage &, const BLRectI &, unsigned int, const BLMatrix2D &>(&BLPattern::create))
        .def("equals", (&BLPattern::equals))
        .def("extendMode", (&BLPattern::extendMode))
        .def("hasMatrix", (&BLPattern::hasMatrix))
        .def("image", (&BLPattern::image))
        .def("isNone", (&BLPattern::isNone))
        .def("matrix", (&BLPattern::matrix))
        .def("matrixType", (&BLPattern::matrixType))
        .def("none", (&BLPattern::none))
        .def("postRotate", py::overload_cast<double>(&BLPattern::postRotate))
        .def("postRotate", py::overload_cast<double, double, double>(&BLPattern::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPoint &>(&BLPattern::postRotate))
        .def("postRotate", py::overload_cast<double, const BLPointI &>(&BLPattern::postRotate))
        .def("postScale", py::overload_cast<double>(&BLPattern::postScale))
        .def("postScale", py::overload_cast<double, double>(&BLPattern::postScale))
        .def("postScale", py::overload_cast<const BLPointI &>(&BLPattern::postScale))
        .def("postScale", py::overload_cast<const BLPoint &>(&BLPattern::postScale))
        .def("postSkew", py::overload_cast<double, double>(&BLPattern::postSkew))
        .def("postSkew", py::overload_cast<const BLPoint &>(&BLPattern::postSkew))
        .def("postTransform", (&BLPattern::postTransform))
        .def("postTranslate", py::overload_cast<double, double>(&BLPattern::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPointI &>(&BLPattern::postTranslate))
        .def("postTranslate", py::overload_cast<const BLPoint &>(&BLPattern::postTranslate))
        .def("reset", (&BLPattern::reset))
        .def("resetArea", (&BLPattern::resetArea))
        .def("resetExtendMode", (&BLPattern::resetExtendMode))
        .def("resetImage", (&BLPattern::resetImage))
        .def("resetMatrix", (&BLPattern::resetMatrix))
        .def("rotate", py::overload_cast<double>(&BLPattern::rotate))
        .def("rotate", py::overload_cast<double, double, double>(&BLPattern::rotate))
        .def("rotate", py::overload_cast<double, const BLPoint &>(&BLPattern::rotate))
        .def("rotate", py::overload_cast<double, const BLPointI &>(&BLPattern::rotate))
        .def("scale", py::overload_cast<double>(&BLPattern::scale))
        .def("scale", py::overload_cast<double, double>(&BLPattern::scale))
        .def("scale", py::overload_cast<const BLPointI &>(&BLPattern::scale))
        .def("scale", py::overload_cast<const BLPoint &>(&BLPattern::scale))
        .def("setArea", (&BLPattern::setArea))
        .def("setExtendMode", (&BLPattern::setExtendMode))
        .def("setImage", py::overload_cast<const BLImage &>(&BLPattern::setImage))
        .def("setImage", py::overload_cast<const BLImage &, const BLRectI &>(&BLPattern::setImage))
        .def("setMatrix", (&BLPattern::setMatrix))
        .def("skew", py::overload_cast<double, double>(&BLPattern::skew))
        .def("skew", py::overload_cast<const BLPoint &>(&BLPattern::skew))
        .def("swap", (&BLPattern::swap))
        .def("transform", (&BLPattern::transform))
        .def("translate", py::overload_cast<double, double>(&BLPattern::translate))
        .def("translate", py::overload_cast<const BLPointI &>(&BLPattern::translate))
        .def("translate", py::overload_cast<const BLPoint &>(&BLPattern::translate));
    py::class_<BLPath>(m, "BLPath")
        .def(py::init<>())
        .def(py::init<const BLPath &>())
        .def(py::init<BLPathImpl *>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("addArc", py::overload_cast<const BLArc &, unsigned int>(&BLPath::addArc))
        .def("addArc", py::overload_cast<const BLArc &, const BLMatrix2D &, unsigned int>(&BLPath::addArc))
        .def("addBox", py::overload_cast<const BLBoxI &, unsigned int>(&BLPath::addBox))
        .def("addBox", py::overload_cast<const BLBox &, unsigned int>(&BLPath::addBox))
        .def("addBox", py::overload_cast<double, double, double, double, unsigned int>(&BLPath::addBox))
        .def("addBoxArray", py::overload_cast<const BLArrayView<BLBoxI> &, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLArrayView<BLBoxI> &, const BLMatrix2D &, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLBoxI *, ULong64_t, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLBoxI *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLArrayView<BLBox> &, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLArrayView<BLBox> &, const BLMatrix2D &, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLBox *, ULong64_t, unsigned int>(&BLPath::addBoxArray))
        .def("addBoxArray", py::overload_cast<const BLBox *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addBoxArray))
        .def("addChord", py::overload_cast<const BLArc &, unsigned int>(&BLPath::addChord))
        .def("addChord", py::overload_cast<const BLArc &, const BLMatrix2D &, unsigned int>(&BLPath::addChord))
        .def("addCircle", py::overload_cast<const BLCircle &, unsigned int>(&BLPath::addCircle))
        .def("addCircle", py::overload_cast<const BLCircle &, const BLMatrix2D &, unsigned int>(&BLPath::addCircle))
        .def("addEllipse", py::overload_cast<const BLEllipse &, unsigned int>(&BLPath::addEllipse))
        .def("addEllipse", py::overload_cast<const BLEllipse &, const BLMatrix2D &, unsigned int>(&BLPath::addEllipse))
        .def("addGeometry", (&BLPath::addGeometry))
        .def("addLine", py::overload_cast<const BLLine &, unsigned int>(&BLPath::addLine))
        .def("addLine", py::overload_cast<const BLLine &, const BLMatrix2D &, unsigned int>(&BLPath::addLine))
        .def("addPath", py::overload_cast<const BLPath &>(&BLPath::addPath))
        .def("addPath", py::overload_cast<const BLPath &, const BLRange &>(&BLPath::addPath))
        .def("addPath", py::overload_cast<const BLPath &, const BLPoint &>(&BLPath::addPath))
        .def("addPath", py::overload_cast<const BLPath &, const BLRange &, const BLPoint &>(&BLPath::addPath))
        .def("addPath", py::overload_cast<const BLPath &, const BLMatrix2D &>(&BLPath::addPath))
        .def("addPath", py::overload_cast<const BLPath &, const BLRange &, const BLMatrix2D &>(&BLPath::addPath))
        .def("addPie", py::overload_cast<const BLArc &, unsigned int>(&BLPath::addPie))
        .def("addPie", py::overload_cast<const BLArc &, const BLMatrix2D &, unsigned int>(&BLPath::addPie))
        .def("addPolygon", py::overload_cast<const BLArrayView<BLPointI> &, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLArrayView<BLPointI> &, const BLMatrix2D &, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLPointI *, ULong64_t, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLPointI *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLArrayView<BLPoint> &, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLArrayView<BLPoint> &, const BLMatrix2D &, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLPoint *, ULong64_t, unsigned int>(&BLPath::addPolygon))
        .def("addPolygon", py::overload_cast<const BLPoint *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addPolygon))
        .def("addPolyline", py::overload_cast<const BLArrayView<BLPointI> &, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLArrayView<BLPointI> &, const BLMatrix2D &, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLPointI *, ULong64_t, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLPointI *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLArrayView<BLPoint> &, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLArrayView<BLPoint> &, const BLMatrix2D &, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLPoint *, ULong64_t, unsigned int>(&BLPath::addPolyline))
        .def("addPolyline", py::overload_cast<const BLPoint *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addPolyline))
        .def("addRect", py::overload_cast<const BLRectI &, unsigned int>(&BLPath::addRect))
        .def("addRect", py::overload_cast<const BLRect &, unsigned int>(&BLPath::addRect))
        .def("addRect", py::overload_cast<double, double, double, double, unsigned int>(&BLPath::addRect))
        .def("addRectArray", py::overload_cast<const BLArrayView<BLRectI> &, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLArrayView<BLRectI> &, const BLMatrix2D &, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLRectI *, ULong64_t, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLRectI *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLArrayView<BLRect> &, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLArrayView<BLRect> &, const BLMatrix2D &, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLRect *, ULong64_t, unsigned int>(&BLPath::addRectArray))
        .def("addRectArray", py::overload_cast<const BLRect *, ULong64_t, const BLMatrix2D &, unsigned int>(&BLPath::addRectArray))
        .def("addRegion", py::overload_cast<const BLRegion &, unsigned int>(&BLPath::addRegion))
        .def("addRegion", py::overload_cast<const BLRegion &, const BLMatrix2D &, unsigned int>(&BLPath::addRegion))
        .def("addReversedPath", py::overload_cast<const BLPath &, unsigned int>(&BLPath::addReversedPath))
        .def("addReversedPath", py::overload_cast<const BLPath &, const BLRange &, unsigned int>(&BLPath::addReversedPath))
        .def("addRoundRect", py::overload_cast<const BLRoundRect &, unsigned int>(&BLPath::addRoundRect))
        .def("addRoundRect", py::overload_cast<const BLRoundRect &, const BLMatrix2D &, unsigned int>(&BLPath::addRoundRect))
        .def("addStrokedPath", py::overload_cast<const BLPath &, const BLRange &, const BLStrokeOptions &, const BLApproximationOptions &>(&BLPath::addStrokedPath))
        .def("addStrokedPath", py::overload_cast<const BLPath &, const BLStrokeOptions &, const BLApproximationOptions &>(&BLPath::addStrokedPath))
        .def("addTriangle", py::overload_cast<const BLTriangle &, unsigned int>(&BLPath::addTriangle))
        .def("addTriangle", py::overload_cast<const BLTriangle &, const BLMatrix2D &, unsigned int>(&BLPath::addTriangle))
        .def("arcQuadrantTo", py::overload_cast<const BLPoint &, const BLPoint &>(&BLPath::arcQuadrantTo))
        .def("arcQuadrantTo", py::overload_cast<double, double, double, double>(&BLPath::arcQuadrantTo))
        .def("arcTo", py::overload_cast<const BLPoint &, const BLPoint &, double, double, bool>(&BLPath::arcTo))
        .def("arcTo", py::overload_cast<double, double, double, double, double, double, bool>(&BLPath::arcTo))
        .def("assign", py::overload_cast<const BLPath &>(&BLPath::assign))
        .def("assignDeep", (&BLPath::assignDeep))
        .def("capacity", (&BLPath::capacity))
        .def("clear", (&BLPath::clear))
        .def("close", (&BLPath::close))
        .def("commandData", (&BLPath::commandData))
        .def("commandDataEnd", (&BLPath::commandDataEnd))
        .def("cubicTo", py::overload_cast<const BLPoint &, const BLPoint &, const BLPoint &>(&BLPath::cubicTo))
        .def("cubicTo", py::overload_cast<double, double, double, double, double, double>(&BLPath::cubicTo))
        .def("ellipticArcTo", py::overload_cast<const BLPoint &, double, bool, bool, const BLPoint &>(&BLPath::ellipticArcTo))
        .def("ellipticArcTo", py::overload_cast<double, double, double, bool, bool, double, double>(&BLPath::ellipticArcTo))
        .def("empty", (&BLPath::empty))
        .def("equals", (&BLPath::equals))
        .def("fitTo", py::overload_cast<const BLRect &, unsigned int>(&BLPath::fitTo))
        .def("fitTo", py::overload_cast<const BLRange &, const BLRect &, unsigned int>(&BLPath::fitTo))
        .def("getBoundingBox", (&BLPath::getBoundingBox))
        .def("getClosestVertex", py::overload_cast<const BLPoint &, double, ULong64_t *>(&BLPath::getClosestVertex, py::const_))
        .def("getClosestVertex", py::overload_cast<const BLPoint &, double, ULong64_t *, double *>(&BLPath::getClosestVertex, py::const_))
        .def("getControlBox", (&BLPath::getControlBox))
        .def("getFigureRange", (&BLPath::getFigureRange))
        .def("getInfoFlags", (&BLPath::getInfoFlags))
        .def("getLastVertex", (&BLPath::getLastVertex))
        .def("hitTest", (&BLPath::hitTest))
        .def("isNone", (&BLPath::isNone))
        .def("lineTo", py::overload_cast<const BLPoint &>(&BLPath::lineTo))
        .def("lineTo", py::overload_cast<double, double>(&BLPath::lineTo))
        .def("moveTo", py::overload_cast<const BLPoint &>(&BLPath::moveTo))
        .def("moveTo", py::overload_cast<double, double>(&BLPath::moveTo))
        .def("none", (&BLPath::none))
        .def("polyTo", (&BLPath::polyTo))
        .def("quadTo", py::overload_cast<const BLPoint &, const BLPoint &>(&BLPath::quadTo))
        .def("quadTo", py::overload_cast<double, double, double, double>(&BLPath::quadTo))
        .def("reserve", (&BLPath::reserve))
        .def("reset", (&BLPath::reset))
        .def("setVertexAt", py::overload_cast<ULong64_t, unsigned int, const BLPoint &>(&BLPath::setVertexAt))
        .def("setVertexAt", py::overload_cast<ULong64_t, unsigned int, double, double>(&BLPath::setVertexAt))
        .def("shrink", (&BLPath::shrink))
        .def("size", (&BLPath::size))
        .def("smoothCubicTo", py::overload_cast<const BLPoint &, const BLPoint &>(&BLPath::smoothCubicTo))
        .def("smoothCubicTo", py::overload_cast<double, double, double, double>(&BLPath::smoothCubicTo))
        .def("smoothQuadTo", py::overload_cast<const BLPoint &>(&BLPath::smoothQuadTo))
        .def("smoothQuadTo", py::overload_cast<double, double>(&BLPath::smoothQuadTo))
        .def("swap", (&BLPath::swap))
        .def("transform", py::overload_cast<const BLMatrix2D &>(&BLPath::transform))
        .def("transform", py::overload_cast<const BLRange &, const BLMatrix2D &>(&BLPath::transform))
        .def("translate", py::overload_cast<const BLPoint &>(&BLPath::translate))
        .def("translate", py::overload_cast<const BLRange &, const BLPoint &>(&BLPath::translate))
        .def("vertexData", (&BLPath::vertexData))
        .def("vertexDataEnd", (&BLPath::vertexDataEnd))
        .def("view", (&BLPath::view));
    py::class_<BLRect>(m, "BLRect")
        .def(py::init<>())
        .def(py::init<const BLRect &>())
        .def(py::init<const BLRectI &>())
        .def(py::init<double, double, double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLRect::equals))
        .def("reset", py::overload_cast<>(&BLRect::reset))
        .def("reset", py::overload_cast<const BLRect &>(&BLRect::reset))
        .def("reset", py::overload_cast<double, double, double, double>(&BLRect::reset));
    py::class_<BLFont>(m, "BLFont")
        .def(py::init<>())
        .def(py::init<const BLFont &>())
        .def(py::init<BLFontImpl *>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("applyGPos", (&BLFont::applyGPos))
        .def("applyGSub", (&BLFont::applyGSub))
        .def("applyKerning", (&BLFont::applyKerning))
        .def("assign", py::overload_cast<const BLFont &>(&BLFont::assign))
        .def("createFromFace", (&BLFont::createFromFace))
        .def("designMetrics", (&BLFont::designMetrics))
        .def("empty", (&BLFont::empty))
        .def("equals", (&BLFont::equals))
        .def("face", (&BLFont::face))
        .def("faceFlags", (&BLFont::faceFlags))
        .def("faceType", (&BLFont::faceType))
        .def("features", (&BLFont::features))
        .def("getGlyphAdvances", (&BLFont::getGlyphAdvances))
        .def("getGlyphBounds", (&BLFont::getGlyphBounds))
        .def("getGlyphOutlines", py::overload_cast<unsigned int, BLPath &, BLResult (*)(BLPathCore *, const void *, void *), void *>(&BLFont::getGlyphOutlines, py::const_))
        .def("getGlyphOutlines", py::overload_cast<unsigned int, const BLMatrix2D &, BLPath &, BLResult (*)(BLPathCore *, const void *, void *), void *>(&BLFont::getGlyphOutlines, py::const_))
        .def("getGlyphRunOutlines", py::overload_cast<const BLGlyphRun &, BLPath &, BLResult (*)(BLPathCore *, const void *, void *), void *>(&BLFont::getGlyphRunOutlines, py::const_))
        .def("getGlyphRunOutlines", py::overload_cast<const BLGlyphRun &, const BLMatrix2D &, BLPath &, BLResult (*)(BLPathCore *, const void *, void *), void *>(&BLFont::getGlyphRunOutlines, py::const_))
        .def("getTextMetrics", (&BLFont::getTextMetrics))
        .def("isNone", (&BLFont::isNone))
        .def("mapTextToGlyphs", py::overload_cast<BLGlyphBuffer &>(&BLFont::mapTextToGlyphs, py::const_))
        .def("mapTextToGlyphs", py::overload_cast<BLGlyphBuffer &, BLGlyphMappingState &>(&BLFont::mapTextToGlyphs, py::const_))
        .def("matrix", (&BLFont::matrix))
        .def("metrics", (&BLFont::metrics))
        .def("none", (&BLFont::none))
        .def("positionGlyphs", (&BLFont::positionGlyphs))
        .def("reset", (&BLFont::reset))
        .def("shape", (&BLFont::shape))
        .def("size", (&BLFont::size))
        .def("stretch", (&BLFont::stretch))
        .def("style", (&BLFont::style))
        .def("swap", (&BLFont::swap))
        .def("unitsPerEm", (&BLFont::unitsPerEm))
        .def("variations", (&BLFont::variations))
        .def("weight", (&BLFont::weight));
    py::class_<BLFontFace>(m, "BLFontFace")
        .def(py::init<>())
        .def(py::init<const BLFontFace &>())
        .def(py::init<BLFontFaceImpl *>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("assign", py::overload_cast<const BLFontFace &>(&BLFontFace::assign))
        .def("createFromData", (&BLFontFace::createFromData))
        .def("createFromFile", (&BLFontFace::createFromFile))
        .def("data", (&BLFontFace::data))
        .def("designMetrics", (&BLFontFace::designMetrics))
        .def("diagFlags", (&BLFontFace::diagFlags))
        .def("empty", (&BLFontFace::empty))
        .def("equals", (&BLFontFace::equals))
        .def("faceFlags", (&BLFontFace::faceFlags))
        .def("faceIndex", (&BLFontFace::faceIndex))
        .def("faceInfo", (&BLFontFace::faceInfo))
        .def("faceType", (&BLFontFace::faceType))
        .def("faceUniqueId", (&BLFontFace::faceUniqueId))
        .def("familyName", (&BLFontFace::familyName))
        .def("familyNameSize", (&BLFontFace::familyNameSize))
        .def("familyNameView", (&BLFontFace::familyNameView))
        .def("fullName", (&BLFontFace::fullName))
        .def("fullNameSize", (&BLFontFace::fullNameSize))
        .def("fullNameView", (&BLFontFace::fullNameView))
        .def("glyphCount", (&BLFontFace::glyphCount))
        .def("hasBaselineYAt0", (&BLFontFace::hasBaselineYAt0))
        .def("hasCharToGlyphMapping", (&BLFontFace::hasCharToGlyphMapping))
        .def("hasFaceFlag", (&BLFontFace::hasFaceFlag))
        .def("hasHorizontalKerning", (&BLFontFace::hasHorizontalKerning))
        .def("hasHorizontalMetrics", (&BLFontFace::hasHorizontalMetrics))
        .def("hasLSBPointXAt0", (&BLFontFace::hasLSBPointXAt0))
        .def("hasOpenTypeFeatures", (&BLFontFace::hasOpenTypeFeatures))
        .def("hasOpenTypeVariations", (&BLFontFace::hasOpenTypeVariations))
        .def("hasPanoseData", (&BLFontFace::hasPanoseData))
        .def("hasTypographicMetrics", (&BLFontFace::hasTypographicMetrics))
        .def("hasTypographicNames", (&BLFontFace::hasTypographicNames))
        .def("hasUnicodeCoverage", (&BLFontFace::hasUnicodeCoverage))
        .def("hasVariationSequences", (&BLFontFace::hasVariationSequences))
        .def("hasVerticalKerning", (&BLFontFace::hasVerticalKerning))
        .def("hasVerticalMetrics", (&BLFontFace::hasVerticalMetrics))
        .def("isLastResortFont", (&BLFontFace::isLastResortFont))
        .def("isNone", (&BLFontFace::isNone))
        .def("isSymbolFont", (&BLFontFace::isSymbolFont))
        .def("none", (&BLFontFace::none))
        .def("outlineType", (&BLFontFace::outlineType))
        .def("panose", (&BLFontFace::panose))
        .def("postScriptName", (&BLFontFace::postScriptName))
        .def("postScriptNameSize", (&BLFontFace::postScriptNameSize))
        .def("postScriptNameView", (&BLFontFace::postScriptNameView))
        .def("reset", (&BLFontFace::reset))
        .def("stretch", (&BLFontFace::stretch))
        .def("style", (&BLFontFace::style))
        .def("subfamilyName", (&BLFontFace::subfamilyName))
        .def("subfamilyNameSize", (&BLFontFace::subfamilyNameSize))
        .def("subfamilyNameView", (&BLFontFace::subfamilyNameView))
        .def("swap", (&BLFontFace::swap))
        .def("unicodeCoverage", (&BLFontFace::unicodeCoverage))
        .def("unitsPerEm", (&BLFontFace::unitsPerEm))
        .def("weight", (&BLFontFace::weight));
    py::class_<BLCircle>(m, "BLCircle")
        .def(py::init<>())
        .def(py::init<const BLCircle &>())
        .def(py::init<double, double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLCircle::equals))
        .def("reset", py::overload_cast<>(&BLCircle::reset))
        .def("reset", py::overload_cast<const BLCircle &>(&BLCircle::reset))
        .def("reset", py::overload_cast<double, double, double>(&BLCircle::reset));
    py::class_<BLGlyphRun>(m, "BLGlyphRun")
        .def(py::init<>())
        .def(py::init<const BLGlyphRun &>())
        .def("empty", (&BLGlyphRun::empty))
        .def("reset", (&BLGlyphRun::reset))
        .def("resetGlyphIdData", (&BLGlyphRun::resetGlyphIdData))
        .def("resetPlacementData", (&BLGlyphRun::resetPlacementData))
        .def("setGlyphData", py::overload_cast<const unsigned short *>(&BLGlyphRun::setGlyphData))
        .def("setGlyphData", py::overload_cast<const unsigned int *>(&BLGlyphRun::setGlyphData))
        .def("setGlyphData", py::overload_cast<const void *, Long64_t>(&BLGlyphRun::setGlyphData));
    py::class_<BLGlyphInfo>(m, "BLGlyphInfo")
        .def(py::init<>())
        .def(py::init<const BLGlyphInfo &>())
        .def("reset", (&BLGlyphInfo::reset));
    py::class_<BLArc>(m, "BLArc")
        .def(py::init<>())
        .def(py::init<const BLArc &>())
        .def(py::init<double, double, double, double, double, double>())
        .def(py::self == py::self)
        .def(py::self != py::self)
        .def("equals", (&BLArc::equals))
        .def("reset", py::overload_cast<>(&BLArc::reset))
        .def("reset", py::overload_cast<const BLArc &>(&BLArc::reset))
        .def("reset", py::overload_cast<double, double, double, double, double, double>(&BLArc::reset));
}